list1_f = [ #Kat Matfield/Bruin Financial
    'agree',
    'affectionate',
    'child',
    'cheer',
    'collab',
    'commit',
    'communal',
    'compassion',
    'connect',
    'considerate',
    'cooperat',
    'co-operat',
    'depend',
    'emotiona',
    'empath',
    'feel',
    'flatterable',
    'gentle',
    'honest',
    'interpersonal',
    'interdependen',
    'interpersona',
    'inter-personal',
    'inter-dependen',
    'inter-persona',
    'kind',
    'kinship',
    'loyal',
    'modesty',
    'nag',
    'nurtur',
    'pleasant',
    'polite',
    'quiet',
    'respon',
    'sensitiv',
    'submissive',
    'support',
    'sympath',
    'tender',
    'together',
    'trust',
    'understand',
    'warm',
    'whin',
    'enthusias',
    'inclusive',
    'yield',
    'share',
    'sharin'
]

list1_m = [ #Kat Matfield/Bruin Financial
    'active',
    'adventurous',
    'aggress',
    'ambitio',
    'analy',
    'assert',
    'athlet',
    'autonom',
    'battle',
    'boast',
    'challeng',
    'champion',
    'compet',
    'confident',
    'courag',
    'decid',
    'decision',
    'decisive',
    'defend',
    'determin',
    'domina',
    'dominant',
    'driven',
    'fearless',
    'fight',
    'force',
    'greedy',
    'head-strong',
    'headstrong',
    'hierarch',
    'hostil',
    'impulsive',
    'independen',
    'individual',
    'intellect',
    'lead',
    'logic',
    'objective',
    'opinion',
    'outspoken',
    'persist',
    'principle',
    'reckless',
    'self-confiden',
    'self-relian',
    'self-sufficien',
    'selfconfiden',
    'selfrelian',
    'selfsufficien',
    'stubborn',
    'superior',
    'unreasonab'
]

list2_f = [ #totaljobs
    'affectionate',
    'cheer',
    'child',
    'commit',
    'communal',
    'compassion',
    'connect',
    'considerate',
    'cooperat',
    'depend',
    'emotiona',
    'empath',
    'feminine',
    'gentle',
    'honest',
    'depend',
    'interdependen',
    'interperson',
    'interpersonal',
    'kind',
    'kinship',
    'loyal',
    'modesty',
    'nurture',
    'pleasant',
    'polite',
    'quiet',
    'respon',
    'responsible',
    'sensitiv',
    'submissive',
    'support',
    'sympathetic',
    'tender',
    'together',
    'trust',
    'understand',
    'warm',
    'whin',
    'yield'
]

list2_m = [ #totaljobs
    'active',
    'adventurous',
    'aggress',
    'ambitio',
    'analy',
    'analytical',
    'assert',
    'athlet',
    'autonom',
    'boast',
    'challeng',
    'competent',
    'competence',
    'competences', 'competitiveness', 'competitively',
    'competitive', 'competencies',
    'competition',
    'compete', 'competing', 'competes',
    'confident',
    'courag',
    'decide',
    'decisi',
    'determin',
    'domina',
    'force',
    'greedy',
    'headstrong',
    'hierarch',
    'hostil',
    'impulsive',
    'independen',
    'individual',
    'intellect',
    'lead',
    'logic',
    'masculine',
    'objective',
    'opinion',
    'outspoken',
    'persist',
    'principle',
    'reckless',
    'self-confident',
    'self-reliant',
    'self-sufficient',
    'stubborn',
    'superior',
]

list3_f = [ #Tom Forth/Slowe
    'hardworking',
    'conscientious',
    'depend',
    'meticulous',
    'thorough',
    'diligen',
    'dedicate',
    'careful',
    'reliab',
    'effort',
    'assiduous',
    'trust',
    'responsible',
    'industrious',
    'busy',
    'work',
    'persist',
    'organiz',
    'disciplined',
    'teach',
    'instruct',
    'educat',
    'train',
    'mentor',
    'supervis',
    'adviser',
    'counselo',
    'syllabus',
    'course',
    'class',
    'service',
    'colleague',
    'citizen',
    'communicate',
    'lectur',
    'student',
    'present',
    'rapport'
]

list3_m = [ #Tom Forth/Slowe
    'excellen',
    'superb',
    'outstanding',
    'unique',
    'exceptional',
    'unparalleled',
    'est',
    'most',
    'wonderful',
    'terrific',
    'fabulous',
    'magnificent',
    'remarkable',
    'extraordinar',
    'amazing',
    'supreme',
    'unmatched',
    'talent',
    'intell',
    'smart',
    'skill',
    'ability',
    'genius',
    'brilliant',
    'bright',
    'brain',
    'aptitude',
    'gift',
    'capacity',
    'propensity',
    'innate',
    'flair',
    'knack',
    'clever',
    'expert',
    'proficient',
    'capable',
    'adept',
    'able',
    'competent',
    'natural',
    'inherent',
    'instinct',
    'adroit',
    'creative',
    'insight',
    'analytical',
    'research',
    'data',
    'study',
    'studies',
    'experiment',
    'scholarship',
    'test',
    'result',
    'finding',
    'publication',
    'publish',
    'vita',
    'method',
    'scien',
    'grant',
    'fund',
    'manuscript',
    'project',
    'journal',
    'theor',
    'discover',
    'contribution'
]

list4_f = [ #beapplied
    "affectionate", "agree", "child", "cheer", "collaborate", "collaborative", "collaboration", "commit", "communal", "communicate", "communicating", "communicator", "compassion", "connect", "considerate",
    "cooperat", "depend", "emotiona", "empath", "enthusiastic", "feminine", "flatterable","feel", "gentle", "honest", "inclusive", "interpersonal",
    "interdependen", "interpersona", "kind", "kinship", "loyal", "modesty", "nag", "nurtur", "pleasant",
    "polite", "quiet", "respon","shar", "sensitiv", "submissive", "support", "sympath", "tender", "together",
    "trust", "understand", "warm", "whin", "yield", "she"
]

list4_m = [ #beapplied
    "active", "adventurous", "agress", "ambitio", "analy", "assert", "athlet", "autonom", "boast",
    "challeng", "compete", "champion", "competes", "competed", "competing", "competent", "competence", "competitive", "competitively", "competitiveness", "confident", "courag", "defend", "decide", "decisive", "decision", "determin", "dominant",
    "domina", "driven", "force", "greedy", "headstrong", "hierarch", "hostil", "impulsive", "independen", "individual",
    "intellect", "lead", "logic", "masculine", "objective", "opinion", "outspoken", "persist", "principle",
    "reckless", "stubborn", "superior", "self-confiden", "self-sufficien", "self-relian"
]

list5_f = [ #eploy
    'affectionate', 'child', 'children', 'cheer', 'cheers', 'cheerful', 'cheerfully', 'commit', 'commitment', 'committed', 'commits', 'communal', 'compassion', 'compassionate', 'connect', 'connects', 'connected', 'considerate', 'cooperate', 'cooperative', 'cooperates', 'co-operates', 'co-operate', 'cooperative', 'depend', 'dependable', 'depends', 'emotional', 'emotionally', 'empathy', 'empathetic', 'empathetically', 'feminine', 'flatter', 'gentle', 'honest', 'interpersonal', 'interdependent', 'interdependence', 'kind', 'kinship', 'loyal', 'loyalty', 'loyally', 'modesty', 'nurture', 'nurtures', 'nurturing', 'nurtured', 'pleasant', 'pleasantly', 'polite', 'quiet', 'quietly', 'respond', 'responsive', 'responsively', 'sensitive', 'sensitively', 'submissive', 'support', 'supports', 'supporting', 'supported', 'sympathy', 'sympathetic', 'sympathetically', 'tender', 'tendering', 'tenders', 'tendered', 'together', 'togetherness', 'trust', 'trusts', 'trusted', 'trustworthy', 'understand', 'understands', 'understanding', 'warm', 'warms', 'yield', 'yields', 'yielding'
]

list5_m = [ #eploy
    'active',
    'adventurous', 'aggressive', 'aggressively', 'aggressiveness',
    'aggression', 'ambition', 'ambitious', 'ambitiously', 'ambitiousness',
    'analytical', 'analytic', 'analyst', 'athlete', 'athletic', 'athletically',
    'athletes', 'athletics', 'autonomy', 'autonomous', 'autonomously', 'boast',
    'boasts', 'boasting', 'boastful', 'boastfully', 'challenge', 'challenging',
    'challenged', 'challenges', 'challengingly', 'competition', 'competitive',
    'competitiveness', 'competitively', 'confident', 'courage', 'courageous',
    'courageously', 'decide', 'decisive', 'decision', 'decisions', 'decisional',
    'determine', 'determines', 'determined', 'determining', 'dominant', 'dominate',
    'dominates', 'dominated', 'dominating', 'force', 'forces', 'forcible', 'forcer',
    'greedy', 'headstrong', 'hierarchy', 'hierarchical', 'hostile', 'hostiles',
    'hostility', 'hostilely', 'impulsive', 'independent', 'independents',
    'independence', 'independency', 'independently', 'individual', 'individuals',
    'individually', 'intellect', 'intellectually', 'intellectual', 'lead', 'leads',
    'leader', 'leading', 'logic', 'masculine', 'objective', 'opinion', 'outspoken',
    'persist', 'principle', 'principles', 'principled', 'reckless', 'stubborn',
    'superior', 'superiorly', 'self-confident', 'self-confidence', 'self-confidently',
    'self-sufficient', 'self-sufficiently', 'self-reliant', 'self-reliance'
]

list6_f = [ #bruin
"agree", "affectionate", "child", "cheer", "collab", "commit", "communal", "compassion", "connect", "considerate", "cooperat", "co-operat", "depend", "emotiona", "empath", "feel", "flatterable", "gentle", "honest", "interpersonal", "interdependen", "interpersona", "inter-personal", "inter-dependent", "inter-persona", "kind", "kinship", "loyal", "modesty", "nag", "nurtur", "pleasant", "polite", "quiet", "respon", "sensitiv", "submissive", "support", "sympath", "tender", "together", "trust", "understand", "warm", "whin", "enthusias", "inclusive", "yield", "share", "sharin", "sharp"
]

list6_m = [ #bruin
"active", "adventurous", "aggress", "ambitio", "analy", "assert", "athlet", "autonom", "battle", "boast", "challeng", "champion", "compet", "confident", "courag", "decid", "decision", "decisive", "defend", "determin", "domina", "dominant", "driven", "fearless", "fight", "force", "greedy", "head-strong", "headstrong", "hierarch", "hostil", "impulsive", "independen", "individual", "intellect", "lead", "logic", "objective", "opinion", "outspoken", "persist", "principle", "reckless", "self-confiden", "self-relian", "self-sufficien", "selfconfiden", "selfrelian", "selfsufficien", "stubborn", "superior", "unreasonab"]


superset_f = ['affectionate', 'agree', 'cheer', 'child', 'co-operat', 'collab', 'commit', 'communal',
              'communicate', 'communicating', 'communicator', 'compassion', 'connect', 'considerate',
              'cooperat', 'depend', 'emotiona', 'empath', 'enthusias', 'feel', 'feminine', 'flatter',
              'gentle', 'honest', 'inclusive', 'inter-dependen', 'inter-persona', 'inter-personal',
              'interdependen', 'interdependence', 'interdependent', 'interperson', 'interpersona',
              'interpersonal', 'kind', 'kinship', 'loyal', 'modesty', 'nag', 'nurtur', 'pleasant',
              'polite', 'quiet', 'quietly', 'respon', 'sensitiv', 'share', 'sharin', 'she', 'submissive',
              'support', 'sympath', 'tender', 'tendered', 'together', 'trust', 'understand','warm', 'whin', 'yield']

superset_m = ['active', 'adventurous', 'aggress', 'ambitio', 'analy', 'assert', 'athlet', 'autonom',
              'battle', 'boast', 'challeng', 'champion', 'compet', 'confident', 'courag', 'decid',
              'decisi','defend', 'determin', 'domina', 'driven', 'fearless', 'fight', 'force', 'forcible',
              'greedy', 'head-strong', 'headstrong', 'hierarch', 'hostil', 'impulsive', 'independen',
              'individual', 'intellect', 'lead', 'logic', 'masculine', 'objective', 'opinion', 'outspoken',
              'persist', 'principle', 'reckless', 'self-confiden', 'self-relian', 'self-sufficien',
              'selfconfiden', 'selfrelian', 'selfsufficien', 'stubborn', 'superior', 'unreasonab']
